import type { HistorySearchQuery } from '../../domain/history-search.js';
import type { ContinueTask } from '../../domain/task-resume.js';
import type { CloneInput } from '../../domain/project-clone.js';
import type { RegisteredProject } from '../../domain/execution.js';
import type { ExecutionResult, OutputChannel } from '../../domain/execution.js';
import type { Attachment, CreateTask, ErrorCode } from '../../domain/contracts.js';
export type Operation = { method: 'enqueuePending'; args: [string, ContinueTask] } | { method: 'listPending' | 'resumePending'; args: [string] } | { method: 'removePending'; args: [string, string] } | { method: 'promotePending'; args: [] } | { method: 'searchHistory'; args: [HistorySearchQuery] } | { method: 'continueTask' | 'findContinuation'; args: [string, ContinueTask] } | { method: 'getTaskSession' | 'getResumeState'; args: [string] } | { method: 'setTaskSession'; args: [string, string] } | { method: 'createClone'; args: [CloneInput, number?] } | { method: 'getClone' | 'cancelClone'; args: [string] } | { method: 'claimClone' | 'interruptClones' | 'listManagedProjects'; args: [] } | { method: 'finishClone'; args: [string, 'succeeded' | 'failed' | 'interrupted' | 'cancelled', RegisteredProject | null, string | null] } | { method: 'createTask'; args: [CreateTask] } | { method: 'getTask' | 'cancelTask' | 'getAttachment'; args: [string] } | { method: 'listTasks'; args: [number] } | { method: 'listEvents'; args: [string, number] } | { method: 'putAttachment'; args: [Attachment] } | { method: 'close' | 'claimNextTask' | 'interruptRunningTasks'; args: [] } | { method: 'queueTask'; args: [string, string] } | { method: 'appendTaskOutput'; args: [string, OutputChannel, string] } | { method: 'finishTask'; args: [string, ExecutionResult] };
export type Request = Operation & { id: number };
export type Reply = { id: number; value?: unknown; error?: ErrorCode };
